

POST http://localhost:8000/api/chat
Content-Type: application/json

{
  "prompt": "What is 100 USD in EUR?"
}


POST http://localhost:8000/api/chat
Content-Type: application/json

{
  "prompt": "I have 5 euros in cash and 20 euros in my bank—what's the total in USD?"
}


POST http://localhost:8000/api/chat
Content-Type: application/json

{
  "prompt": "If I get paid 3500 GBP per month, how much is that in Canadian dollars?"
}

###

POST http://localhost:8000/api/chat
Content-Type: application/json

{
  "prompt": "I want to convert 150 Swiss Francs and 80 USD into euros, how much do I get?"
}


POST http://localhost:8000/api/chat
Content-Type: application/json

{
  "prompt": "Is ¥10,000 (Japanese Yen) enough to buy a $60 USD video game?"
}
